#!/usr/local/bin/python

# IGN : RFGENERATION
IGN = {
    '2600': '2600',
    '3DO': '3DO',
    '3DS': '3DS',
    'Arcade': 'Arcade',
    'Android': 'Android',
    'CD-i': 'CD-i',
    'Cell': 'Cell',
    'DC': 'Sega Dreamcast',
    'DSi': 'DSi',
    'GB': 'Nintendo Game Boy',
    'GBA': 'Nintendo Game Boy Advance',
    'GBC': 'Nintendo Game Boy Color',
    'Gen': 'Sega Genesis',
    'GCN': 'Nintendo GameCube',
    'Jag-CD': 'Jag-CD',
    'iPad': 'iPad',
    'iPhone': 'iPhone',
    'Laser': 'Laser',
    'Linux': 'Linux',
    'Mac': 'Mac',
    'N64': 'Nintendo 64',
    'NDS': 'NDS',
    'NES': 'Nintendo',
    'NNG': 'Nokia N-Gage',
    'PC': 'PC',
    'PDA': 'PDA',
    'PS': 'Sony Playstation',
    'PS2': 'Sony Playstation 2',
    'PS3': 'Sony PlayStation 3',
    'PS4': 'PS4',
    'PSP': 'Sony PSP',
    'Saturn': 'Sega Saturn',
    'Sega-CD': 'Sega Mega CD',
    'SNES': 'Super Nintendo',
    'TG16': 'Turbo Graphx 16',
    'Vita': 'Sony Vita',
    'Web': 'Web',
    'Wii': 'Nintendo Wii',
    'Wii U': 'Nintendo Wii U',
    'Xbox': 'Microsoft Xbox',
    'Xbox One': 'Microsoft Xbox One',
    'Xbox 360': 'Microsoft Xbox 360',
}
